### ISSUE TITLE
Passphrased keys?

### ISSUE THREAD

**Issue by jdelStrother** [mdsol/docker-ssh-exec#2]
Hi - do you have any thoughts on using this when your key is protected by a passphrase?  I spent quite a while trying to figure out ways of getting an unprotected id_rsa via ssh-agent, without any luck.

**Comment by benton** [comment]
I _think_ it is possible, using two instances of the software on different ports, one for the key and one for the secret. The resulting syntax in the `Dockerfile` would probably be so unpleasant as to defeat the purpose -- but maybe not. I'll think about it and try it with my own password-protected key.

I'm trying to keep the tool SSH-agnostic _(even though it's in the name - doh!)_, since technically it just reads (or serves) some bytes over the network, then writes them to the filesystem, runs a command, and then deletes them. But adding SSH-specific code to handle encrypted keys nicely might be worth sacrificing this design purity, because it's a really common and laudable use case. After all, the whole point of the tool is to maintain security.

So I'll see what I can do.

**BUT** -- I just got back from DockerCon2016 and a Solutions Architect in Docker's "Ask the Experts" booth assured me that this trick is possible using only `docker-compose`! I am following up to get a working example that meets the following requirements:

- the secret used to perform checkout, whether password or SSH key, must not be embedded in the resulting docker image in any way. The build environment is free to pass this info to docker-compose by ENV, shared volume, or any other means that does _not_ violate this prime constraint; also...
- docker only in the build environment (no Ruby, bundler, etc. from outside a container)! However, using the docker-compose YAML equivalent of `docker run -v .:/my_app --entrypoint=/some/binary some/image` to invoke these tools from the build environment _is_ legit, because then we're still just using Docker's software for the build.

If he delivers, I'll post here.

**Comment by benton** [comment]
@jdelStrother Well, the Docker Solutions Architect did not yet respond to me, and someone else asked me for this feature, so I took a crack at it. Can you please try out the latest release and let me know if it works for you? You can just `docker pull mdsol/docker-ssh-exec:0.5.2` or `mdsol/docker-ssh-exec:latest` – There are no changes on the client side, so there's no need to rebuild any Docker source images that might have version 0.5.1.

In version 0.5.2, you can set the decryption passphrase for your private key on the server side, with either the `-pwd` command-line flag, or the `RSA_KEY_PWD` environment variable. The server log will  print something like `Decrypting private key` when it uses the passphrase, which is every time a client requests it (so you can swap the key out without restarting the server).

Good luck!
-b

**Comment by jdelStrother** [comment]
Awesome - works great, thanks.

**Comment by peetasan** [comment]
Unfortunately this didn't work for me: added the env var RSA_KEY_PWD before starting the server in docker, then when I run `docker-ssh-exec git` command I get:

```
Listening on UDP port 1067...
Received key request from 172.17.0.2, sending key.
Decrypting private key with passphrase...
Error decrypting PEM-encoded secret: x509: decryption password incorrect
```

Then  I get the passphrase prompt from the client, it accepts my passphrase. Not sure if it matter, but my key is encrypted with AES-128-CBC.

BTW I tried version 0.5.1 with my manually (with openssl) decrypted key, it worked, but I'd really like to keep my key encrypted.
